### PR TITLE
Update steam.nim

### PR DESCRIPTION
**Pull request by levshx**
...

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Thanks, are you interested in help maintaining it ?, I can give you access, etc. 😃

**Review by juancarlospaco — APPROVED** [review]
:+1:

**Comment by levshx** [comment]
> Спасибо, вы заинтересованы в помощи в его обслуживании? Я могу предоставить вам доступ и т. Д.

yes, I would like to. But I'm afraid to screw up, if this is not a problem for you :D
I have a little experience with nim

**Comment by juancarlospaco** [comment]
Make changes via Pull Requests, and I can review before merge and everything will be ok.

**Pull request merged**
